# Site settings
title: Miguel García Arquitectura y Diseño
email: mgarquitectura@arquitecturamg.com
description: Miguel García - Architecture and design studio in Cancún, México. Miguel García designs commercial and residential projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Miguel García
email: mgarquitectura@arquitecturamg.com
facebook_username: MiguelGarciaAyD
twitter_username:
github_username:
address:
  - line: Cancún, Quintana Roo, México
  - line:
  # Feel free to add more lines here 
telephone: +52 998 158 2576
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown

