# Site settings
title: Miguel Garcia Architecture and Design
email:
description: Miguel Garcia - Architecture and design studio in Cancun, Mexico. Miguel Garcia designs commercial and residential projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Miguel Garcia
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown

