# Site settings
title: Miguel Garcia Architecture and Design
email:
description: Miguel Garcia - Architecture and design studio in Cancun, Mexico. Miguel Garcia designs commercial and residential projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Miguel Garcia
email: mg_architecture-and-design@hotmail.com
facebook_username: MiguelGarciaAyD
twitter_username:
github_username:
address: Cancún, Quintana Roo, México
  - line:
  - line:
  # Feel free to add more lines here 
telephone: +52 998 158 2576
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
